version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dev_environment_dockerfile
    volumes:
      - .:/app
    environment:
      - VIRTUAL_ENV=/venv

      - PATH=/venv/bin:$PATH
    ports:
      - "8000:8000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    stdin_open: true
    tty: true

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10
