defaults:
  - _self_

# Paths
data_path: "../cropped_dataset/CX1"
schema_path: "./annotations.json"
path_to_model_save: "../Transformer"

# Training parameters
batch_size: 1000
epochs: 500
learning_rate: 1e-3
test_split: 0.2
shuffle: true
seed: 0
sequence_length: 10
downsample: true
# Transformer parameters
transformer:
  input_dim: 8192
  d_model: 512
  nhead: 8
  num_layers: 6
  num_classes: 1
# StepLR scheduler parameters
stepLR:
  step_size: 100
  gamma: 0.1
